/**
 * GENERATED by scripts/fetch-domain-photos.mjs — do not hand-edit.
 *
 * Attribution for the four card photos in "Globally acclaimed domains". Every
 * one is CC BY, which *requires* credit, so the section renders this. Removing
 * the credit line means removing the photos.
 */
export const domainPhotoCredits = [
  {
    "key": "management",
    "alt": "A young professional in a blazer, smiling",
    "focal": "50% 16%",
    "title": "business woman",
    "creator": "citirecruitment",
    "source": "https://www.flickr.com/photo.gne?id=14387367072",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/"
  },
  {
    "key": "stem",
    "alt": "University students gathered around laboratory equipment",
    "focal": "50% 32%",
    "title": "Truman University Students Visit NASA Goddard",
    "creator": "NASA Goddard Photo and Video",
    "source": "https://www.flickr.com/photo.gne?id=4500255129",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/"
  },
  {
    "key": "undergraduate",
    "alt": "A graduating student in cap and gown at a commencement ceremony",
    "focal": "50% 24%",
    "title": "College of DuPage 2014 Commencement Ceremony",
    "creator": "COD Newsroom",
    "source": "https://www.flickr.com/photo.gne?id=14222463315",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/"
  },
  {
    "key": "internships",
    "alt": "A young woman working at a laptop",
    "focal": "50% 60%",
    "title": "Geschäftsfrau arbeitet am Laptop im modernen Büro",
    "creator": "Ivan Radic",
    "source": "https://www.flickr.com/photo.gne?id=47977792257",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/"
  }
];
