/**
 * Destination cards for the "One path, multiple destinations" section.
 *
 * GENERATED by scripts/fetch-destinations.mjs — do not hand-edit; re-run it.
 * Card copy is read from upgrad.com/study-abroad. `photo` is deliberately null
 * on every entry: their cards use licensed stock photography we have no right
 * to, so the component falls back to a flag panel. Put licensed images in
 * public/study-abroad/cities/ and set the field to use them.
 *
 * `pin` is {x, y} as a percentage of public/study-abroad/world-map.svg, read
 * off that file's own country geometry — see scripts/map-pins.json.
 */
export const studyAbroadDestinations = [
  {
    "name": "USA",
    "slug": "united-states",
    "iso": "us",
    "courses": "Engg, AI/ML, Data Science, MBA",
    "highlight": "#1 Economy with 3.5M STEM Jobs",
    "topChoice": true,
    "photo": null,
    "pin": {
      "x": 20.72,
      "y": 25.97
    }
  },
  {
    "name": "Germany",
    "slug": "germany",
    "iso": "de",
    "courses": "Engg, Healthcare, MBA, Finance",
    "highlight": "Europe's #1 Economy with 1 Million Jobs",
    "topChoice": false,
    "photo": null,
    "pin": {
      "x": 50.1,
      "y": 18.45
    }
  },
  {
    "name": "France",
    "slug": "france",
    "iso": "fr",
    "courses": "MBA, Hospitality, Luxury, SCM, MKT",
    "highlight": "Up to 5 Years of PSW Visa",
    "topChoice": false,
    "photo": null,
    "pin": {
      "x": 47.91,
      "y": 21.28
    }
  },
  {
    "name": "Finland",
    "slug": "finland",
    "iso": "fi",
    "courses": "ICT, Informatics, Game Development",
    "highlight": "Europe's #1 Tech & Gaming Hub",
    "topChoice": false,
    "photo": null,
    "pin": {
      "x": 54.39,
      "y": 11.48
    }
  },
  {
    "name": "UK",
    "slug": "united-kingdom",
    "iso": "gb",
    "courses": "Law, Business, Design, Public Policy",
    "highlight": "1 year Masters at Top Universities",
    "topChoice": false,
    "photo": null,
    "pin": {
      "x": 46.64,
      "y": 17.03
    }
  },
  {
    "name": "Canada",
    "slug": "canada",
    "iso": "ca",
    "courses": "Data Science, Analytics, Engg",
    "highlight": "Top Study Hub with 3 Year PGWP",
    "topChoice": false,
    "photo": null,
    "pin": {
      "x": 19.75,
      "y": 16.11
    }
  },
  {
    "name": "Australia",
    "slug": "australia",
    "iso": "au",
    "courses": "IT, Nursing, GreenTech, Engineering",
    "highlight": "Up to 5 Years of PSW Visa",
    "topChoice": false,
    "photo": null,
    "pin": {
      "x": 84.08,
      "y": 66.66
    }
  },
  {
    "name": "Ireland",
    "slug": "ireland",
    "iso": "ie",
    "courses": "ICT Hub",
    "highlight": "Thriving $19B+ ICT market",
    "topChoice": false,
    "photo": null,
    "pin": {
      "x": 45.07,
      "y": 17.15
    }
  }
];
