/**
 * GENERATED by scripts/fetch-support-photos.mjs — do not hand-edit.
 *
 * Attribution for the "360° support system" accordion's photos. Every one is
 * CC BY, which *requires* credit; it renders in the combined "Photos:" line
 * under "Globally acclaimed domains". Removing them from that line means
 * removing the photos.
 */
export const supportPhotoCredits = [
  {
    "key": "counseling",
    "alt": "Two students talking across a table, one holding a tablet",
    "focal": "50% 50%",
    "title": "Education - Creative Commons",
    "creator": "NEC Corporation of America",
    "source": "https://www.flickr.com/photo.gne?id=16412471166",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/"
  },
  {
    "key": "scholarship",
    "alt": "A graduate in cap and gown giving a thumbs-up at a commencement ceremony",
    "focal": "50% 40%",
    "title": "College of DuPage 2014 Commencement Ceremony 85",
    "creator": "COD Newsroom",
    "source": "https://www.flickr.com/photo.gne?id=14035801608",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/"
  },
  {
    "key": "ielts",
    "alt": "Hands typing an essay on a laptop in a library",
    "focal": "50% 50%",
    "title": "Education - Creative Commons",
    "creator": "NEC Corporation of America",
    "source": "https://www.flickr.com/photo.gne?id=16437509602",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/"
  },
  {
    "key": "loan",
    "alt": "A fan of banknotes beside a calculator",
    "focal": "50% 50%",
    "title": "Saving Money",
    "creator": "free pictures of money",
    "source": "https://www.flickr.com/photo.gne?id=17309001591",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/"
  },
  {
    "key": "visa",
    "alt": "A passport page filled with immigration and visa stamps",
    "focal": "50% 50%",
    "title": "Passport stamps",
    "creator": "madmack66",
    "source": "https://www.flickr.com/photo.gne?id=2094132134",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/"
  }
];
